import type { Metadata } from 'next';
import './globals.css';
import { roboto, code } from '@/public/font';
import Navigation from '@/components/layout/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${roboto.variable} ${code.variable} antialiased font-code relative`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
