/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppStudyRouteImport } from './routes/_app/study'
import { Route as AppWorkRouteImport } from './routes/_app/work'
import { Route as AppWritingRouteRouteImport } from './routes/_app/writing/route'
import { Route as AppWritingIndexRouteImport } from './routes/_app/writing/index'
import { Route as AppWritingArticlesRouteRouteImport } from './routes/_app/writing/articles/route'
import { Route as AppWritingCarouselsRouteRouteImport } from './routes/_app/writing/carousels/route'
import { Route as AppWritingPostsRouteRouteImport } from './routes/_app/writing/posts/route'
import { Route as AppWritingArticlesIndexRouteImport } from './routes/_app/writing/articles/index'
import { Route as AppWritingArticlesArticle_idRouteImport } from './routes/_app/writing/articles/$article_id'
import { Route as AppWritingCarouselsIndexRouteImport } from './routes/_app/writing/carousels/index'
import { Route as AppWritingCarouselsCarousel_idRouteImport } from './routes/_app/writing/carousels/$carousel_id'
import { Route as AppWritingPostsIndexRouteImport } from './routes/_app/writing/posts/index'
import { Route as AppWritingPostsPost_idRouteImport } from './routes/_app/writing/posts/$post_id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWritingRouteRoute = AppWritingRouteRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWritingIndexRoute = AppWritingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWritingRouteRoute,
} as any)
const AppWritingArticlesRouteRoute = AppWritingArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppWritingRouteRoute,
} as any)
const AppWritingCarouselsRouteRoute =
  AppWritingCarouselsRouteRouteImport.update({
    id: '/carousels',
    path: '/carousels',
    getParentRoute: () => AppWritingRouteRoute,
  } as any)
const AppWritingPostsRouteRoute = AppWritingPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppWritingRouteRoute,
} as any)
const AppWritingArticlesIndexRoute = AppWritingArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWritingArticlesRouteRoute,
} as any)
const AppWritingArticlesArticle_idRoute =
  AppWritingArticlesArticle_idRouteImport.update({
    id: '/$article_id',
    path: '/$article_id',
    getParentRoute: () => AppWritingArticlesRouteRoute,
  } as any)
const AppWritingCarouselsIndexRoute =
  AppWritingCarouselsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWritingCarouselsRouteRoute,
  } as any)
const AppWritingCarouselsCarousel_idRoute =
  AppWritingCarouselsCarousel_idRouteImport.update({
    id: '/$carousel_id',
    path: '/$carousel_id',
    getParentRoute: () => AppWritingCarouselsRouteRoute,
  } as any)
const AppWritingPostsIndexRoute = AppWritingPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWritingPostsRouteRoute,
} as any)
const AppWritingPostsPost_idRoute = AppWritingPostsPost_idRouteImport.update({
  id: '/$post_id',
  path: '/$post_id',
  getParentRoute: () => AppWritingPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/writing': typeof AppWritingRouteRouteWithChildren
  '/contact': typeof AppContactRoute
  '/map': typeof AppMapRoute
  '/projects': typeof AppProjectsRoute
  '/study': typeof AppStudyRoute
  '/work': typeof AppWorkRoute
  '/writing/articles': typeof AppWritingArticlesRouteRouteWithChildren
  '/writing/carousels': typeof AppWritingCarouselsRouteRouteWithChildren
  '/writing/posts': typeof AppWritingPostsRouteRouteWithChildren
  '/writing/': typeof AppWritingIndexRoute
  '/writing/articles/$article_id': typeof AppWritingArticlesArticle_idRoute
  '/writing/carousels/$carousel_id': typeof AppWritingCarouselsCarousel_idRoute
  '/writing/posts/$post_id': typeof AppWritingPostsPost_idRoute
  '/writing/articles/': typeof AppWritingArticlesIndexRoute
  '/writing/carousels/': typeof AppWritingCarouselsIndexRoute
  '/writing/posts/': typeof AppWritingPostsIndexRoute
}
export interface FileRoutesByTo {
  '/contact': typeof AppContactRoute
  '/map': typeof AppMapRoute
  '/projects': typeof AppProjectsRoute
  '/study': typeof AppStudyRoute
  '/work': typeof AppWorkRoute
  '/': typeof AppIndexRoute
  '/writing': typeof AppWritingIndexRoute
  '/writing/articles/$article_id': typeof AppWritingArticlesArticle_idRoute
  '/writing/carousels/$carousel_id': typeof AppWritingCarouselsCarousel_idRoute
  '/writing/posts/$post_id': typeof AppWritingPostsPost_idRoute
  '/writing/articles': typeof AppWritingArticlesIndexRoute
  '/writing/carousels': typeof AppWritingCarouselsIndexRoute
  '/writing/posts': typeof AppWritingPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/writing': typeof AppWritingRouteRouteWithChildren
  '/_app/contact': typeof AppContactRoute
  '/_app/map': typeof AppMapRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/study': typeof AppStudyRoute
  '/_app/work': typeof AppWorkRoute
  '/_app/': typeof AppIndexRoute
  '/_app/writing/articles': typeof AppWritingArticlesRouteRouteWithChildren
  '/_app/writing/carousels': typeof AppWritingCarouselsRouteRouteWithChildren
  '/_app/writing/posts': typeof AppWritingPostsRouteRouteWithChildren
  '/_app/writing/': typeof AppWritingIndexRoute
  '/_app/writing/articles/$article_id': typeof AppWritingArticlesArticle_idRoute
  '/_app/writing/carousels/$carousel_id': typeof AppWritingCarouselsCarousel_idRoute
  '/_app/writing/posts/$post_id': typeof AppWritingPostsPost_idRoute
  '/_app/writing/articles/': typeof AppWritingArticlesIndexRoute
  '/_app/writing/carousels/': typeof AppWritingCarouselsIndexRoute
  '/_app/writing/posts/': typeof AppWritingPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/writing'
    | '/contact'
    | '/map'
    | '/projects'
    | '/study'
    | '/work'
    | '/writing/articles'
    | '/writing/carousels'
    | '/writing/posts'
    | '/writing/'
    | '/writing/articles/$article_id'
    | '/writing/carousels/$carousel_id'
    | '/writing/posts/$post_id'
    | '/writing/articles/'
    | '/writing/carousels/'
    | '/writing/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/map'
    | '/projects'
    | '/study'
    | '/work'
    | '/'
    | '/writing'
    | '/writing/articles/$article_id'
    | '/writing/carousels/$carousel_id'
    | '/writing/posts/$post_id'
    | '/writing/articles'
    | '/writing/carousels'
    | '/writing/posts'
  id:
    | '__root__'
    | '/_app'
    | '/_app/writing'
    | '/_app/contact'
    | '/_app/map'
    | '/_app/projects'
    | '/_app/study'
    | '/_app/work'
    | '/_app/'
    | '/_app/writing/articles'
    | '/_app/writing/carousels'
    | '/_app/writing/posts'
    | '/_app/writing/'
    | '/_app/writing/articles/$article_id'
    | '/_app/writing/carousels/$carousel_id'
    | '/_app/writing/posts/$post_id'
    | '/_app/writing/articles/'
    | '/_app/writing/carousels/'
    | '/_app/writing/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/study': {
      id: '/_app/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/writing': {
      id: '/_app/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AppWritingRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/writing/': {
      id: '/_app/writing/'
      path: '/'
      fullPath: '/writing/'
      preLoaderRoute: typeof AppWritingIndexRouteImport
      parentRoute: typeof AppWritingRouteRoute
    }
    '/_app/writing/articles': {
      id: '/_app/writing/articles'
      path: '/articles'
      fullPath: '/writing/articles'
      preLoaderRoute: typeof AppWritingArticlesRouteRouteImport
      parentRoute: typeof AppWritingRouteRoute
    }
    '/_app/writing/carousels': {
      id: '/_app/writing/carousels'
      path: '/carousels'
      fullPath: '/writing/carousels'
      preLoaderRoute: typeof AppWritingCarouselsRouteRouteImport
      parentRoute: typeof AppWritingRouteRoute
    }
    '/_app/writing/posts': {
      id: '/_app/writing/posts'
      path: '/posts'
      fullPath: '/writing/posts'
      preLoaderRoute: typeof AppWritingPostsRouteRouteImport
      parentRoute: typeof AppWritingRouteRoute
    }
    '/_app/writing/articles/': {
      id: '/_app/writing/articles/'
      path: '/'
      fullPath: '/writing/articles/'
      preLoaderRoute: typeof AppWritingArticlesIndexRouteImport
      parentRoute: typeof AppWritingArticlesRouteRoute
    }
    '/_app/writing/articles/$article_id': {
      id: '/_app/writing/articles/$article_id'
      path: '/$article_id'
      fullPath: '/writing/articles/$article_id'
      preLoaderRoute: typeof AppWritingArticlesArticle_idRouteImport
      parentRoute: typeof AppWritingArticlesRouteRoute
    }
    '/_app/writing/carousels/': {
      id: '/_app/writing/carousels/'
      path: '/'
      fullPath: '/writing/carousels/'
      preLoaderRoute: typeof AppWritingCarouselsIndexRouteImport
      parentRoute: typeof AppWritingCarouselsRouteRoute
    }
    '/_app/writing/carousels/$carousel_id': {
      id: '/_app/writing/carousels/$carousel_id'
      path: '/$carousel_id'
      fullPath: '/writing/carousels/$carousel_id'
      preLoaderRoute: typeof AppWritingCarouselsCarousel_idRouteImport
      parentRoute: typeof AppWritingCarouselsRouteRoute
    }
    '/_app/writing/posts/': {
      id: '/_app/writing/posts/'
      path: '/'
      fullPath: '/writing/posts/'
      preLoaderRoute: typeof AppWritingPostsIndexRouteImport
      parentRoute: typeof AppWritingPostsRouteRoute
    }
    '/_app/writing/posts/$post_id': {
      id: '/_app/writing/posts/$post_id'
      path: '/$post_id'
      fullPath: '/writing/posts/$post_id'
      preLoaderRoute: typeof AppWritingPostsPost_idRouteImport
      parentRoute: typeof AppWritingPostsRouteRoute
    }
  }
}

interface AppWritingArticlesRouteRouteChildren {
  AppWritingArticlesArticle_idRoute: typeof AppWritingArticlesArticle_idRoute
  AppWritingArticlesIndexRoute: typeof AppWritingArticlesIndexRoute
}

const AppWritingArticlesRouteRouteChildren: AppWritingArticlesRouteRouteChildren =
  {
    AppWritingArticlesArticle_idRoute: AppWritingArticlesArticle_idRoute,
    AppWritingArticlesIndexRoute: AppWritingArticlesIndexRoute,
  }

const AppWritingArticlesRouteRouteWithChildren =
  AppWritingArticlesRouteRoute._addFileChildren(
    AppWritingArticlesRouteRouteChildren,
  )

interface AppWritingCarouselsRouteRouteChildren {
  AppWritingCarouselsCarousel_idRoute: typeof AppWritingCarouselsCarousel_idRoute
  AppWritingCarouselsIndexRoute: typeof AppWritingCarouselsIndexRoute
}

const AppWritingCarouselsRouteRouteChildren: AppWritingCarouselsRouteRouteChildren =
  {
    AppWritingCarouselsCarousel_idRoute: AppWritingCarouselsCarousel_idRoute,
    AppWritingCarouselsIndexRoute: AppWritingCarouselsIndexRoute,
  }

const AppWritingCarouselsRouteRouteWithChildren =
  AppWritingCarouselsRouteRoute._addFileChildren(
    AppWritingCarouselsRouteRouteChildren,
  )

interface AppWritingPostsRouteRouteChildren {
  AppWritingPostsPost_idRoute: typeof AppWritingPostsPost_idRoute
  AppWritingPostsIndexRoute: typeof AppWritingPostsIndexRoute
}

const AppWritingPostsRouteRouteChildren: AppWritingPostsRouteRouteChildren = {
  AppWritingPostsPost_idRoute: AppWritingPostsPost_idRoute,
  AppWritingPostsIndexRoute: AppWritingPostsIndexRoute,
}

const AppWritingPostsRouteRouteWithChildren =
  AppWritingPostsRouteRoute._addFileChildren(AppWritingPostsRouteRouteChildren)

interface AppWritingRouteRouteChildren {
  AppWritingArticlesRouteRoute: typeof AppWritingArticlesRouteRouteWithChildren
  AppWritingCarouselsRouteRoute: typeof AppWritingCarouselsRouteRouteWithChildren
  AppWritingPostsRouteRoute: typeof AppWritingPostsRouteRouteWithChildren
  AppWritingIndexRoute: typeof AppWritingIndexRoute
}

const AppWritingRouteRouteChildren: AppWritingRouteRouteChildren = {
  AppWritingArticlesRouteRoute: AppWritingArticlesRouteRouteWithChildren,
  AppWritingCarouselsRouteRoute: AppWritingCarouselsRouteRouteWithChildren,
  AppWritingPostsRouteRoute: AppWritingPostsRouteRouteWithChildren,
  AppWritingIndexRoute: AppWritingIndexRoute,
}

const AppWritingRouteRouteWithChildren = AppWritingRouteRoute._addFileChildren(
  AppWritingRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppWritingRouteRoute: typeof AppWritingRouteRouteWithChildren
  AppContactRoute: typeof AppContactRoute
  AppMapRoute: typeof AppMapRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppStudyRoute: typeof AppStudyRoute
  AppWorkRoute: typeof AppWorkRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWritingRouteRoute: AppWritingRouteRouteWithChildren,
  AppContactRoute: AppContactRoute,
  AppMapRoute: AppMapRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppStudyRoute: AppStudyRoute,
  AppWorkRoute: AppWorkRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
